package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketSearchHistory;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketSearchHistory selectOneByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketSearchHistory> selectByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketSearchHistory record, @Param("example") MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketSearchHistory record, @Param("example") MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketSearchHistory record);
}