package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketFootprint;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketFootprint selectOneByExample(MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketFootprint> selectByExample(MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketFootprint record, @Param("example") MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketFootprint record, @Param("example") MarketFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_footprint
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketFootprint record);
}