package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketKeyword;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketKeyword selectOneByExample(MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketKeyword> selectByExample(MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketKeyword record, @Param("example") MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketKeyword record, @Param("example") MarketKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_keyword
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketKeyword record);
}