package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketCoupon;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketCoupon selectOneByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketCoupon> selectByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketCoupon record, @Param("example") MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketCoupon record, @Param("example") MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketCoupon record);
}