package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketRole;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketRole selectOneByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketRole> selectByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketRole record, @Param("example") MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketRole record, @Param("example") MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketRole record);
}