package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketCollect;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketCollect selectOneByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketCollect> selectByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketCollect record, @Param("example") MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketCollect record, @Param("example") MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketCollect record);
}