package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketOrder;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketOrder selectOneByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketOrder> selectByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketOrder record, @Param("example") MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketOrder record, @Param("example") MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketOrder record);

    Integer countUnpaidOrdersByUsername(String principal);

    Integer countUnshipOrdersByUsername(String principal);

    Integer countUnreceivedOrdersByUsername(String principal);

    Integer countUncommentOrdersByUsername(String principal);
}