package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketAd;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketAd selectOneByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketAd> selectByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketAd record, @Param("example") MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketAd record, @Param("example") MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketAd record);
}