package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketPermission;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketPermission selectOneByExample(MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketPermission> selectByExample(MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketPermission record, @Param("example") MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketPermission record, @Param("example") MarketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketPermission record);
}