package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketUser;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketUser selectOneByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketUser> selectByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketUser record, @Param("example") MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketUser record, @Param("example") MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketUser record);
}