package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketOrderGoods;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketOrderGoods selectOneByExample(MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketOrderGoods> selectByExample(MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketOrderGoods record, @Param("example") MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketOrderGoods record, @Param("example") MarketOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order_goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketOrderGoods record);
}