package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketLog;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketLog selectOneByExample(MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketLog> selectByExample(MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketLog record, @Param("example") MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketLog record, @Param("example") MarketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_log
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketLog record);
}