package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketIssue;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    long countByExample(MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByExample(MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insert(MarketIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int insertSelective(MarketIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketIssue selectOneByExample(MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    List<MarketIssue> selectByExample(MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    MarketIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketIssue record, @Param("example") MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByExample(@Param("record") MarketIssue record, @Param("example") MarketIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(MarketIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_issue
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    int updateByPrimaryKey(MarketIssue record);
}