package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketGoods;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketGoodsExample;

import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    long countByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insert(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insertSelective(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketGoods selectOneByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketGoods selectOneByExampleWithBLOBs(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    List<MarketGoods> selectByExampleWithBLOBs(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    List<MarketGoods> selectByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExample(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKeySelective(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKey(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByExample(@Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByPrimaryKey(Integer id);

    List<MarketGoods> selectGoodsByIdList(@Param("idList") List<Integer> idList);
}