package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketBrand;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    long countByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insert(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insertSelective(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketBrand selectOneByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    List<MarketBrand> selectByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketBrand record, @Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExample(@Param("record") MarketBrand record, @Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKeySelective(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKey(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByExample(@Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByPrimaryKey(Integer id);
}