package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketStorage;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketStorage selectOneByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketStorage> selectByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketStorage record, @Param("example") MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketStorage record, @Param("example") MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketStorage record);
}