package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketAdmin;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    long countByExample(MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByExample(MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insert(MarketAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int insertSelective(MarketAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketAdmin selectOneByExample(MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    List<MarketAdmin> selectByExample(MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    MarketAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketAdmin record, @Param("example") MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByExample(@Param("record") MarketAdmin record, @Param("example") MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKeySelective(MarketAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int updateByPrimaryKey(MarketAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByExample(@Param("example") MarketAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_admin
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    int logicalDeleteByPrimaryKey(Integer id);
}