package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketSystem;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketSystem selectOneByExample(MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketSystem> selectByExample(MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketSystem record, @Param("example") MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketSystem record, @Param("example") MarketSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_system
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketSystem record);
}