package com.laoyancheng.www.wxmarketbackend.db.mapper;

import com.laoyancheng.www.wxmarketbackend.db.domain.MarketComment;
import com.laoyancheng.www.wxmarketbackend.db.domain.MarketCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    long countByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insert(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int insertSelective(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketComment selectOneByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    List<MarketComment> selectByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    MarketComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExampleSelective(@Param("record") MarketComment record, @Param("example") MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByExample(@Param("record") MarketComment record, @Param("example") MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKeySelective(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    int updateByPrimaryKey(MarketComment record);
}