package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.math.BigDecimal;
import java.util.Date;

public class MarketGrouponRules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_groupon_rules
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_groupon_rules
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.goods_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.goods_name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.pic_url
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.discount
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.discount_member
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer discountMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.expire_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_groupon_rules.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.id
     *
     * @return the value of market_groupon_rules.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.id
     *
     * @param id the value for market_groupon_rules.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.goods_id
     *
     * @return the value of market_groupon_rules.goods_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.goods_id
     *
     * @param goodsId the value for market_groupon_rules.goods_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.goods_name
     *
     * @return the value of market_groupon_rules.goods_name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.goods_name
     *
     * @param goodsName the value for market_groupon_rules.goods_name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.pic_url
     *
     * @return the value of market_groupon_rules.pic_url
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.pic_url
     *
     * @param picUrl the value for market_groupon_rules.pic_url
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.discount
     *
     * @return the value of market_groupon_rules.discount
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.discount
     *
     * @param discount the value for market_groupon_rules.discount
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.discount_member
     *
     * @return the value of market_groupon_rules.discount_member
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getDiscountMember() {
        return discountMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.discount_member
     *
     * @param discountMember the value for market_groupon_rules.discount_member
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setDiscountMember(Integer discountMember) {
        this.discountMember = discountMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.expire_time
     *
     * @return the value of market_groupon_rules.expire_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.expire_time
     *
     * @param expireTime the value for market_groupon_rules.expire_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.status
     *
     * @return the value of market_groupon_rules.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.status
     *
     * @param status the value for market_groupon_rules.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.add_time
     *
     * @return the value of market_groupon_rules.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.add_time
     *
     * @param addTime the value for market_groupon_rules.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.update_time
     *
     * @return the value of market_groupon_rules.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.update_time
     *
     * @param updateTime the value for market_groupon_rules.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_groupon_rules
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_groupon_rules.deleted
     *
     * @return the value of market_groupon_rules.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_groupon_rules.deleted
     *
     * @param deleted the value for market_groupon_rules.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table market_groupon_rules
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_groupon_rules
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public String getName() {
            return this.name;
        }
    }
}