package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketCouponUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_coupon_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_coupon_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.user_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.coupon_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.used_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date usedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.start_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.end_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.order_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.id
     *
     * @return the value of market_coupon_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.id
     *
     * @param id the value for market_coupon_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.user_id
     *
     * @return the value of market_coupon_user.user_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.user_id
     *
     * @param userId the value for market_coupon_user.user_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.coupon_id
     *
     * @return the value of market_coupon_user.coupon_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.coupon_id
     *
     * @param couponId the value for market_coupon_user.coupon_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.status
     *
     * @return the value of market_coupon_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.status
     *
     * @param status the value for market_coupon_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.used_time
     *
     * @return the value of market_coupon_user.used_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.used_time
     *
     * @param usedTime the value for market_coupon_user.used_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.start_time
     *
     * @return the value of market_coupon_user.start_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.start_time
     *
     * @param startTime the value for market_coupon_user.start_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.end_time
     *
     * @return the value of market_coupon_user.end_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.end_time
     *
     * @param endTime the value for market_coupon_user.end_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.order_id
     *
     * @return the value of market_coupon_user.order_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.order_id
     *
     * @param orderId the value for market_coupon_user.order_id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.add_time
     *
     * @return the value of market_coupon_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.add_time
     *
     * @param addTime the value for market_coupon_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.update_time
     *
     * @return the value of market_coupon_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.update_time
     *
     * @param updateTime the value for market_coupon_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon_user.deleted
     *
     * @return the value of market_coupon_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon_user.deleted
     *
     * @param deleted the value for market_coupon_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table market_coupon_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_coupon_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public String getName() {
            return this.name;
        }
    }
}