package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.admin
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.ip
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.type
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.action
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.status
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.result
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_log.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.id
     *
     * @return the value of market_log.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.id
     *
     * @param id the value for market_log.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.admin
     *
     * @return the value of market_log.admin
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.admin
     *
     * @param admin the value for market_log.admin
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setAdmin(String admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.ip
     *
     * @return the value of market_log.ip
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.ip
     *
     * @param ip the value for market_log.ip
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.type
     *
     * @return the value of market_log.type
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.type
     *
     * @param type the value for market_log.type
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.action
     *
     * @return the value of market_log.action
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.action
     *
     * @param action the value for market_log.action
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.status
     *
     * @return the value of market_log.status
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.status
     *
     * @param status the value for market_log.status
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.result
     *
     * @return the value of market_log.result
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.result
     *
     * @param result the value for market_log.result
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.comment
     *
     * @return the value of market_log.comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.comment
     *
     * @param comment the value for market_log.comment
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.add_time
     *
     * @return the value of market_log.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.add_time
     *
     * @param addTime the value for market_log.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.update_time
     *
     * @return the value of market_log.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.update_time
     *
     * @param updateTime the value for market_log.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_log.deleted
     *
     * @return the value of market_log.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_log.deleted
     *
     * @param deleted the value for market_log.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}