package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketGoodsSpecification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.goods_id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.specification
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.value
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.pic_url
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_goods_specification.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.id
     *
     * @return the value of market_goods_specification.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.id
     *
     * @param id the value for market_goods_specification.id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.goods_id
     *
     * @return the value of market_goods_specification.goods_id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.goods_id
     *
     * @param goodsId the value for market_goods_specification.goods_id
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.specification
     *
     * @return the value of market_goods_specification.specification
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.specification
     *
     * @param specification the value for market_goods_specification.specification
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.value
     *
     * @return the value of market_goods_specification.value
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.value
     *
     * @param value the value for market_goods_specification.value
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.pic_url
     *
     * @return the value of market_goods_specification.pic_url
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.pic_url
     *
     * @param picUrl the value for market_goods_specification.pic_url
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.add_time
     *
     * @return the value of market_goods_specification.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.add_time
     *
     * @param addTime the value for market_goods_specification.add_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.update_time
     *
     * @return the value of market_goods_specification.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.update_time
     *
     * @param updateTime the value for market_goods_specification.update_time
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_goods_specification.deleted
     *
     * @return the value of market_goods_specification.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_goods_specification.deleted
     *
     * @param deleted the value for market_goods_specification.deleted
     *
     * @mbg.generated Wed Dec 27 20:04:49 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}