package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.math.BigDecimal;
import java.util.Date;

public class MarketTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.title
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.subtitle
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.price
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.read_count
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer[] goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_topic.content
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.id
     *
     * @return the value of market_topic.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.id
     *
     * @param id the value for market_topic.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.title
     *
     * @return the value of market_topic.title
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.title
     *
     * @param title the value for market_topic.title
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.subtitle
     *
     * @return the value of market_topic.subtitle
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.subtitle
     *
     * @param subtitle the value for market_topic.subtitle
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.price
     *
     * @return the value of market_topic.price
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.price
     *
     * @param price the value for market_topic.price
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.read_count
     *
     * @return the value of market_topic.read_count
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.read_count
     *
     * @param readCount the value for market_topic.read_count
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setReadCount(String readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.pic_url
     *
     * @return the value of market_topic.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.pic_url
     *
     * @param picUrl the value for market_topic.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.sort_order
     *
     * @return the value of market_topic.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.sort_order
     *
     * @param sortOrder the value for market_topic.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.goods
     *
     * @return the value of market_topic.goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer[] getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.goods
     *
     * @param goods the value for market_topic.goods
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setGoods(Integer[] goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.add_time
     *
     * @return the value of market_topic.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.add_time
     *
     * @param addTime the value for market_topic.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.update_time
     *
     * @return the value of market_topic.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.update_time
     *
     * @param updateTime the value for market_topic.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.deleted
     *
     * @return the value of market_topic.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.deleted
     *
     * @param deleted the value for market_topic.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_topic.content
     *
     * @return the value of market_topic.content
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_topic.content
     *
     * @param content the value for market_topic.content
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}