package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.role_id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_permission.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.id
     *
     * @return the value of market_permission.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.id
     *
     * @param id the value for market_permission.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.role_id
     *
     * @return the value of market_permission.role_id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.role_id
     *
     * @param roleId the value for market_permission.role_id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.permission
     *
     * @return the value of market_permission.permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.permission
     *
     * @param permission the value for market_permission.permission
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.add_time
     *
     * @return the value of market_permission.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.add_time
     *
     * @param addTime the value for market_permission.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.update_time
     *
     * @return the value of market_permission.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.update_time
     *
     * @param updateTime the value for market_permission.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_permission.deleted
     *
     * @return the value of market_permission.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_permission.deleted
     *
     * @param deleted the value for market_permission.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}