package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.keywords
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.pid
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.icon_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.level
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Byte sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_category.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.id
     *
     * @return the value of market_category.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.id
     *
     * @param id the value for market_category.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.name
     *
     * @return the value of market_category.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.name
     *
     * @param name the value for market_category.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.keywords
     *
     * @return the value of market_category.keywords
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.keywords
     *
     * @param keywords the value for market_category.keywords
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.desc
     *
     * @return the value of market_category.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.desc
     *
     * @param desc the value for market_category.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.pid
     *
     * @return the value of market_category.pid
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.pid
     *
     * @param pid the value for market_category.pid
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.icon_url
     *
     * @return the value of market_category.icon_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.icon_url
     *
     * @param iconUrl the value for market_category.icon_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.pic_url
     *
     * @return the value of market_category.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.pic_url
     *
     * @param picUrl the value for market_category.pic_url
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.level
     *
     * @return the value of market_category.level
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.level
     *
     * @param level the value for market_category.level
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.sort_order
     *
     * @return the value of market_category.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.sort_order
     *
     * @param sortOrder the value for market_category.sort_order
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.add_time
     *
     * @return the value of market_category.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.add_time
     *
     * @param addTime the value for market_category.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.update_time
     *
     * @return the value of market_category.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.update_time
     *
     * @param updateTime the value for market_category.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_category.deleted
     *
     * @return the value of market_category.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_category.deleted
     *
     * @param deleted the value for market_category.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}