package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.util.Date;

public class MarketUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table market_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.username
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.password
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.gender
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.birthday
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.last_login_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.last_login_ip
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.user_level
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Byte userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.nickname
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.mobile
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.avatar
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.weixin_openid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String weixinOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.session_key
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String sessionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_user.salt
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.id
     *
     * @return the value of market_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.id
     *
     * @param id the value for market_user.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.username
     *
     * @return the value of market_user.username
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.username
     *
     * @param username the value for market_user.username
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.password
     *
     * @return the value of market_user.password
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.password
     *
     * @param password the value for market_user.password
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.gender
     *
     * @return the value of market_user.gender
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.gender
     *
     * @param gender the value for market_user.gender
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.birthday
     *
     * @return the value of market_user.birthday
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.birthday
     *
     * @param birthday the value for market_user.birthday
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.last_login_time
     *
     * @return the value of market_user.last_login_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.last_login_time
     *
     * @param lastLoginTime the value for market_user.last_login_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.last_login_ip
     *
     * @return the value of market_user.last_login_ip
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.last_login_ip
     *
     * @param lastLoginIp the value for market_user.last_login_ip
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.user_level
     *
     * @return the value of market_user.user_level
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Byte getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.user_level
     *
     * @param userLevel the value for market_user.user_level
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUserLevel(Byte userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.nickname
     *
     * @return the value of market_user.nickname
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.nickname
     *
     * @param nickname the value for market_user.nickname
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.mobile
     *
     * @return the value of market_user.mobile
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.mobile
     *
     * @param mobile the value for market_user.mobile
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.avatar
     *
     * @return the value of market_user.avatar
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.avatar
     *
     * @param avatar the value for market_user.avatar
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.weixin_openid
     *
     * @return the value of market_user.weixin_openid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getWeixinOpenid() {
        return weixinOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.weixin_openid
     *
     * @param weixinOpenid the value for market_user.weixin_openid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setWeixinOpenid(String weixinOpenid) {
        this.weixinOpenid = weixinOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.session_key
     *
     * @return the value of market_user.session_key
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.session_key
     *
     * @param sessionKey the value for market_user.session_key
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.status
     *
     * @return the value of market_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.status
     *
     * @param status the value for market_user.status
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.add_time
     *
     * @return the value of market_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.add_time
     *
     * @param addTime the value for market_user.add_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.update_time
     *
     * @return the value of market_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.update_time
     *
     * @param updateTime the value for market_user.update_time
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.deleted
     *
     * @return the value of market_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.deleted
     *
     * @param deleted the value for market_user.deleted
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_user.salt
     *
     * @return the value of market_user.salt
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_user.salt
     *
     * @param salt the value for market_user.salt
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table market_user
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table market_user
         *
         * @mbg.generated Fri Dec 29 16:04:46 CST 2023
         */
        public String getName() {
            return this.name;
        }
    }
}