package com.laoyancheng.www.wxmarketbackend.db.domain;

import java.math.BigDecimal;
import java.util.Date;

public class MarketCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.tag
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.total
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.discount
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.min
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private BigDecimal min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.limit
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.status
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.goods_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.goods_value
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Integer[] goodsValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.code
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.time_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short timeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.days
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Short days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.start_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.end_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_coupon.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.id
     *
     * @return the value of market_coupon.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.id
     *
     * @param id the value for market_coupon.id
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.name
     *
     * @return the value of market_coupon.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.name
     *
     * @param name the value for market_coupon.name
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.desc
     *
     * @return the value of market_coupon.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.desc
     *
     * @param desc the value for market_coupon.desc
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.tag
     *
     * @return the value of market_coupon.tag
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.tag
     *
     * @param tag the value for market_coupon.tag
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.total
     *
     * @return the value of market_coupon.total
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.total
     *
     * @param total the value for market_coupon.total
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.discount
     *
     * @return the value of market_coupon.discount
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.discount
     *
     * @param discount the value for market_coupon.discount
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.min
     *
     * @return the value of market_coupon.min
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.min
     *
     * @param min the value for market_coupon.min
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setMin(BigDecimal min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.limit
     *
     * @return the value of market_coupon.limit
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.limit
     *
     * @param limit the value for market_coupon.limit
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setLimit(Short limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.type
     *
     * @return the value of market_coupon.type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.type
     *
     * @param type the value for market_coupon.type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.status
     *
     * @return the value of market_coupon.status
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.status
     *
     * @param status the value for market_coupon.status
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.goods_type
     *
     * @return the value of market_coupon.goods_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.goods_type
     *
     * @param goodsType the value for market_coupon.goods_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setGoodsType(Short goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.goods_value
     *
     * @return the value of market_coupon.goods_value
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Integer[] getGoodsValue() {
        return goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.goods_value
     *
     * @param goodsValue the value for market_coupon.goods_value
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setGoodsValue(Integer[] goodsValue) {
        this.goodsValue = goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.code
     *
     * @return the value of market_coupon.code
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.code
     *
     * @param code the value for market_coupon.code
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.time_type
     *
     * @return the value of market_coupon.time_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.time_type
     *
     * @param timeType the value for market_coupon.time_type
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setTimeType(Short timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.days
     *
     * @return the value of market_coupon.days
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Short getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.days
     *
     * @param days the value for market_coupon.days
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDays(Short days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.start_time
     *
     * @return the value of market_coupon.start_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.start_time
     *
     * @param startTime the value for market_coupon.start_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.end_time
     *
     * @return the value of market_coupon.end_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.end_time
     *
     * @param endTime the value for market_coupon.end_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.add_time
     *
     * @return the value of market_coupon.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.add_time
     *
     * @param addTime the value for market_coupon.add_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.update_time
     *
     * @return the value of market_coupon.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.update_time
     *
     * @param updateTime the value for market_coupon.update_time
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_coupon.deleted
     *
     * @return the value of market_coupon.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_coupon.deleted
     *
     * @param deleted the value for market_coupon.deleted
     *
     * @mbg.generated Thu Dec 28 23:26:32 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}