package com.laoyancheng.www.wxmarketbackend.db.domain;

public class MarketRegion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_region.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_region.pid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_region.name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_region.type
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_region.code
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    private Integer code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_region.id
     *
     * @return the value of market_region.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_region.id
     *
     * @param id the value for market_region.id
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_region.pid
     *
     * @return the value of market_region.pid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_region.pid
     *
     * @param pid the value for market_region.pid
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_region.name
     *
     * @return the value of market_region.name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_region.name
     *
     * @param name the value for market_region.name
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_region.type
     *
     * @return the value of market_region.type
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_region.type
     *
     * @param type the value for market_region.type
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_region.code
     *
     * @return the value of market_region.code
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_region.code
     *
     * @param code the value for market_region.code
     *
     * @mbg.generated Fri Dec 29 16:04:46 CST 2023
     */
    public void setCode(Integer code) {
        this.code = code;
    }
}